### ISSUE TITLE
Amazon unsupported

### ISSUE THREAD

**Issue by Berzerker** [Rayquaza01/authenticator#5]
When trying to add my key from Amazon's 2FA implementation, it doesn't show up in the list. The key is quite long, 52 characters in the base32 secret key. Seems like anything over 40 characters causes this issue.

Also, adding it causes anything added after it to not show up on the list either.

**Comment by Rayquaza01** [comment]
This should be fixed on version 1.0.5, which is available on AMO now.

**Comment by Berzerker** [comment]
Fairly certain I'm running 1.0.5 and it's still not working.

**Comment by Rayquaza01** [comment]
Does it still not appear in the list, or is it giving the wrong code?

**Comment by Berzerker** [comment]
It and anything added afterwords doesn’t appear on the list, just has a tiny box with a timer and a settings button.

**Comment by Rayquaza01** [comment]
With the browser console open (Menu > Web Developer > Browser Console), is anything logged when you click the toolbar icon?

Specifically, the entry would look like `TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.` or `TypeError: res.otp_list is undefined`.

**Comment by Berzerker** [comment]
So it looks like my version wasn't actually updated, it refreshed but all of my codes were wrong. I emptied it all and tried to import my json again, but now it shows nothing, and console gives me "TypeError: res.otp_list is undefined"

**Comment by Berzerker** [comment]
Update: I tried importing it again, disabling/uninstalling/undoing, and some combination of that ended up with the correct codes...so it looks like it's working now. I have actually 0 idea how to reproduce this though lol.

Also, I noticed there's no "Import" button to actually confirm the import once you choose a file, is it supposed to be automatic?

**Comment by Rayquaza01** [comment]
Glad that it's working now.

And yes, as soon as a file is selected it will be imported automatically.
